spring.application.name=rts-server
spring.datasource.url=jdbc:mysql://localhost:3306/rts_game?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
jwt.secret=change_this_secret_key_to_long_random_string_123456789
jwt.access-expiration-ms=3600000
jwt.refresh-expiration-ms=604800000